openapi: 3.0.0
info:
  title: Kanban-Project-Backend-API
  version: 16.05.2022
paths:
  /api/data.json:
    get:
      operationId: 0e03a18240c0d3119d6a991f98230cd1
      responses:
        '200':
          description: 'The data'
